[workspace]
resolver = "2"
members = [
    "tardyai",
    "chapter1",
]

[workspace.dependencies]
dfdx = { version = "0.13", features = ["safetensors"] }
log = { version = "0.4" }
env_logger = { version = "0.10.1" }

